# Generated by Django 4.1.1 on 2022-09-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomersDetialsModel',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(help_text='customer_name', max_length=100)),
                ('customer_ph_number', models.IntegerField(help_text='customer_ph_number')),
                ('custome_password', models.CharField(help_text='custome_password', max_length=8)),
            ],
            options={
                'db_table': 'customers_details',
            },
        ),
    ]
