# Generated by Django 4.1.1 on 2022-09-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersdetialsmodel',
            name='customer_ph_number',
            field=models.IntegerField(help_text='customer_ph_number', max_length=10),
        ),
    ]
