# Generated by Django 4.1.1 on 2022-09-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0004_customerfeedbackmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersdetialsmodel',
            name='customer_ph_number',
            field=models.BigIntegerField(),
        ),
    ]
