# Generated by Django 4.1.1 on 2022-10-01 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0005_alter_customersdetialsmodel_customer_ph_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackmodel',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customersdetialsmodel'),
        ),
    ]
