# Generated by Django 4.1.1 on 2022-10-04 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0004_menudetialsmodel_item_type'),
        ('customerapp', '0006_customerfeedbackmodel_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMyBooking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('booking_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurantapp.menudetialsmodel')),
            ],
            options={
                'db_table': 'customer_booking',
            },
        ),
    ]
