# Generated by Django 4.1.1 on 2022-10-04 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0007_customermybooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermybooking',
            name='booking_date',
            field=models.DateField(default=datetime.datetime(2022, 10, 4, 11, 58, 36, 237180), null=True),
        ),
    ]
