# Generated by Django 4.1.1 on 2022-10-04 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0008_alter_customermybooking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermybooking',
            old_name='booking_creator',
            new_name='menu_details',
        ),
        migrations.AddField(
            model_name='customermybooking',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customersdetialsmodel'),
        ),
        migrations.AlterField(
            model_name='customermybooking',
            name='booking_date',
            field=models.DateField(null=True),
        ),
    ]
