# Generated by Django 4.1.1 on 2022-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0009_rename_booking_creator_customermybooking_menu_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermybooking',
            name='booking_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
