# Generated by Django 4.1.1 on 2022-10-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0010_alter_customermybooking_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermybooking',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
