# Generated by Django 4.1.1 on 2022-10-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0011_customermybooking_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersdetialsmodel',
            name='custome_password',
        ),
        migrations.AddField(
            model_name='customersdetialsmodel',
            name='customer_password',
            field=models.CharField(help_text='custome_password', max_length=12, null=True),
        ),
    ]
