# Generated by Django 4.1.1 on 2022-10-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0012_remove_customersdetialsmodel_custome_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedbackmodel',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customerapp.customermybooking'),
        ),
    ]
