# Generated by Django 4.1.1 on 2022-09-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuDetialsModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(help_text='item name', max_length=100)),
                ('item_price', models.IntegerField(help_text='price')),
                ('item_offer_zone', models.IntegerField(help_text='offer zone')),
                ('item_description', models.TextField(help_text='description', max_length=500)),
                ('item_image', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'db_table': 'menu_details',
            },
        ),
    ]
