# Generated by Django 4.1.1 on 2022-09-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetialsmodel',
            name='item_offer_zone',
            field=models.CharField(help_text='offer zone', max_length=100),
        ),
    ]
