# Generated by Django 4.1.1 on 2022-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantapp', '0002_alter_menudetialsmodel_item_offer_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menudetialsmodel',
            name='item_image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
